language: java
jdk:
  - oraclejdk8

# Enable container-based architecture.
sudo: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # Travis is on 64bit and there will be a cryptic aapt error w/o these libs.
      # For native code tests, we need some additional libraries if we are in a 64-bit environment.
      - libgd2-xpm
      - libc6:i386
      - libstdc++6:i386
      - zlib1g:i386
      - g++-5
      - groovy
      # Getting compile errors on javac 1.8.0_31-b13
      - oracle-java8-installer

before_install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
  - gcc --version && g++ --version
  # Limit Ant's and Buck's memory usage to avoid the OOM killer.
  - export ANT_OPTS='-Xmx500m'
  - export BUCK_EXTRA_JAVA_ARGS='-Xmx500m'
  # Set up the Android environment.
  - export NDK_HOME=${HOME}/android-ndk-linux
  - ./scripts/travisci_install_android_ndk.sh
  - export ANDROID_HOME=${HOME}/android-sdk-linux
  - ./scripts/travisci_install_android_sdk.sh
  # Install go 1.5
  - eval "$(gimme 1.5)"
  - echo -e "[go]\n  root = ${GOROOT}" >> .buckconfig
  # Set up the Groovy environment
  - export GROOVY_HOME=/usr/share/groovy/

cache:
  directories:
    - $HOME/android-ndk-linux
    - $HOME/android-sdk-linux

notifications:
    slack: buckbuild:TnJN80RxFaSAuCGswsnWLdoj

script:
  - ./scripts/travisci_run.sh
