language: android
jdk:
  - oraclejdk8
env:
  - CI_ACTION=build
  - CI_ACTION=unit
  - CI_ACTION=integration
  - CI_ACTION=heavy_integration
  - CI_ACTION=ant

dist: trusty

# Enable container-based architecture.
sudo: false

android:
  components:
  - tools
  - platform-tools
  - build-tools-23.0.2
  - android-23
  - addon-google_apis-google-23
  - android-21
  - addon-google_apis-google-21
  - extra-android-support

addons:
  apt:
    packages:
      - ant
      # Travis is on 64bit and there will be a cryptic aapt error w/o these libs.
      # For native code tests, we need some additional libraries if we are in a 64-bit environment.
      - libgd2-xpm-dev
      - libc6:i386
      - libstdc++6:i386
      - zlib1g:i386
      - groovy
        # We rely on -gno-record-gcc-switches which was added in 4.7.
      - gcc
      - g++
      # Getting compile errors on javac 1.8.0_31-b13
      - oracle-java8-installer
      # Haskell tests require GHC (and at least version 7.6).
      - ghc
      # base ghc package does not include dynamic libraries
      # https://stackoverflow.com/a/11711501/1548477
      - ghc-dynamic

before_install:
  # Limit Ant's and Buck's memory usage to avoid the OOM killer.
  - export ANT_OPTS='-Xmx500m'
  - echo '-Xmx500m' > .buckjavaargs.local
  # Set up the Android environment.
  - export NDK_HOME=${HOME}/android-ndk-linux
  - ./scripts/travisci_install_android_ndk.sh
  # Install go 1.8, required for cgo -srcdir flag to work
  - eval "$(gimme 1.8)"
  - echo -e "[go]\n  root = ${GOROOT}" >> .buckconfig.local
  # Set up the Groovy environment
  - export GROOVY_HOME=/usr/share/groovy/

# Buck dependencies are checked in, so no need to download dependencies
install: true

# https://docs.travis-ci.com/user/caching#Things-not-to-cache
# https://docs.travis-ci.com/user/caching#Explicitly-disabling-caching
cache:
  directories:
    - $HOME/ndk_cache

notifications:
  slack:
    rooms:
      secure: SYKQV9DT55kHf5Mpe6g5a3NmGXJb5E7kWiLulRp+EmKDIhf3lVmxGbx4Yr/TKZixbNILsPzhhiB56V0H+0mAgMpygVXaq4M9eSHKLljJEmEdeLKmQaRuOUikMOkpLsHw/epvmqrsvlb3yVpsJZZhhHmi9B0oQc0AnjpL/qLBaZE=

script:
  - ./scripts/travisci_run.sh
