version: 2

aliases:
  - &restore-android-sdk
    keys:
      - android-sdk-{{ checksum "scripts/android-sdk-setup.sh" }}
      - android-sdk
  - &save-android-sdk
    paths:
      - /opt/android
    key: android-sdk-{{ checksum "scripts/android-sdk-setup.sh" }}
  - &android-setup
     name: Setup Android SDK
     command: ./scripts/android-sdk-setup.sh
  - &apt-dependencies
    name: Install APT dependencies
    command: |
      apt-get -qq -y update
      apt install -qq -y --no-install-recommends ant gcc g++ git groovy python ssh-client unzip wget
  - &run-ci-script
    name: Run CI script
    command: |
      echo '-Xmx500m' > .buckjavaargs.local
      ./scripts/travisci_run.sh

references:
  workspace_root: &workspace_root
      ~/buck
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

defaults: &defaults
   docker:
     - image: openjdk:8-slim
   working_directory: *workspace_root

jobs:
  build:
    <<: *defaults
    environment:
      CI_ACTION: build
      ANDROID_HOME: /opt/android
     
    steps:
      - run: *apt-dependencies
      - checkout
      - restore-cache: *restore-android-sdk
      - run: *android-setup
      - save-cache: *save-android-sdk
      - run: *run-ci-script
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - ant-out
            - buck-out

  unit:
    <<: *defaults
    environment:
      ANDROID_HOME: /opt/android
      CI_ACTION: unit
      GROOVY_HOME: /usr/share/groovy/

    steps:
      - run: *apt-dependencies
      - *attach_workspace
      - restore-cache: *restore-android-sdk
      - run: *android-setup
      - save-cache: *save-android-sdk
      - run: *run-ci-script

workflows:
   version: 2
   build_and_test:
     jobs:
       - build
       - unit:
          requires:
            - build
