version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-23-alpha

    working_directory: ~/repo

    environment:
      CI_ACTION: unit
      GROOVY_HOME: /usr/share/groovy/
    
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt update -y -qq
            sudo apt install --no-install-recommends -y -qq ant groovy
      - run: ./scripts/travisci_run.sh
