version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-23-alpha

    working_directory: ~/repo

    environment:
      CI_ACTION: build
    
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt update -y -qq
            sudo apt install --no-install-recommends -y -qq ant
      - run: ./scripts/travisci_run.sh

  unit:
    docker:
      - image: circleci/android:api-23-alpha

    working_directory: ~/repo

    environment:
      CI_ACTION: unit
      GROOVY_HOME: /usr/share/groovy/
    
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt update -y -qq
            sudo apt install --no-install-recommends -y -qq ant groovy
      - run: ./scripts/travisci_run.sh
  
  ant:
    docker:
      - image: circleci/android:api-23-alpha

    working_directory: ~/repo

    environment:
      CI_ACTION: ant
    
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt update -y -qq
            sudo apt install --no-install-recommends -y -qq ant
      - run: ./scripts/travisci_run.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - unit
      - ant