version: 2

jobs:
  ci_build:
    environment:
      WORKINGDIR: "~/buck"
      ANDROIDSDK: "~/android-sdk"
    working_directory: ${WORKINGDIR}
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Install Android SDK
          command: |
            mkdir ${ANDROIDSDK}
            cd ${ANDROIDSDK}
            wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
            unzip sdk-tools-linux-4333796.zip
            export PATH=${ANDROIDSDK}/tools/bin:$PATH
            echo 'y' |sdkmanager --install tools
            echo 'y' |sdkmanager --install platform-tools
            echo 'y' |sdkmanager --install "build-tools;23.0.2"
            echo 'y' |sdkmanager --install "platforms;android-23"
      - run:
          name: Install GoLang 1.10.1
          command: |
            cd ~
            wget https://storage.googleapis.com/golang/go1.10.1.linux-amd64.tar.gz
            sudo tar -xzf go1.10.1.linux-amd64.tar.gz -C /usr/local
            go version
      - run:
          name: Install Python 3.6.2
          command: |
            pyenv install -s 3.6.2
            pyenv global 3.6.2 system
            python --version
      - run:
          name: Run Ant Build
          command: |
            cd ${WORKINGDIR}
            set -eux
            export TERM=dumb
            export ANT_OPTS='-Xmx1000m'
            ant
      - run:
          name: Run Buck Build
          command: |
            cd ${WORKINGDIR}
            echo '-Xmx750m' > .buckjavaargs.local
            export PATH=${ANDROIDSDK}/tools/bin:$PATH
            export PATH="$(pyenv root)/shims:$PATH"
            ./bin/buck build buck --out ./new_buck.pex
            export BUCK_NUM_THREADS=3
            ./new_buck.pex build --num-threads=${BUCK_NUM_THREADS} src/... test/...
workflows:
  version: 2
  all_jobs:
    jobs:
      - ci_build
