aliases:
  - &run-ci-script
    name: Run CI script
    command: |
      ./scripts/travisci_run.sh

defaults: &defaults
  docker:
    - image: circleci/android:api-23-alpha
  working_directory: ~/buck

version: 2
jobs:
  build:
    <<: *defaults
    environment:
      CI_ACTION: build
    
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt update -y -qq
            sudo apt install --no-install-recommends -y -qq ant
      - run: *run-ci-script

  unit:
    <<: *defaults
    environment:
      CI_ACTION: unit
      GROOVY_HOME: /usr/share/groovy/

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt update -y -qq
            sudo apt install --no-install-recommends -y -qq ant groovy
      - run: *run-ci-script

  ant:
    <<: *defaults
    environment:
      CI_ACTION: ant

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt update -y -qq
            sudo apt install --no-install-recommends -y -qq ant
      - run: ./scripts/travisci_run.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - unit
      - ant
