defaults: &defaults
  docker:
    - image: circleci/android:api-23-alpha
  working_directory: ~/buck

version: 2
jobs:
  build:
    <<: *defaults
    environment:
      CI_ACTION: build
    
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt update -y -qq
            sudo apt install --no-install-recommends -y -qq ant
      - run: ./scripts/travisci_run.sh

  unit:
    <<: *defaults
    environment:
      CI_ACTION: unit
      GROOVY_HOME: /usr/share/groovy/

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt update -y -qq
            sudo apt install --no-install-recommends -y -qq ant groovy
      - run: ./scripts/travisci_run.sh

  ant:
    <<: *defaults
    environment:
      CI_ACTION: ant

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt update -y -qq
            sudo apt install --no-install-recommends -y -qq ant
      - run: ./scripts/travisci_run.sh

  ndk_17:
    <<: *defaults
    docker:
      - image: circleci/android:api-23-ndk-r17b

    environment:
      CI_ACTION: android_ndk_17

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt update -y -qq
            sudo apt install --no-install-recommends -y -qq ant
      - run: ./scripts/travisci_run.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - unit