aliases:
  - &apt-dependencies
    name: Install APT dependencies
    command: |
      apt update -y
      apt install -y --no-install-recommends ant git groovy python unzip wget
  - &run-ci-script
    name: Run CI script
    command: |
      ./scripts/travisci_run.sh

defaults: &defaults
  docker:
    - image: openjdk:8-slim
  working_directory: ~/buck

version: 2
jobs:
  build:
    <<: *defaults
    environment:
      CI_ACTION: build
    
    steps:
      - run: *apt-dependencies
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt update -y -qq
            sudo apt install --no-install-recommends -y -qq ant
      - run: *run-ci-script

  unit:
    <<: *defaults
    environment:
      CI_ACTION: unit
      GROOVY_HOME: /usr/share/groovy/

    steps:
      - run: *apt-dependencies
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt update -y -qq
            sudo apt install --no-install-recommends -y -qq ant groovy
      - run: *run-ci-script

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - unit
