name: Build
on: [push, pull_request]

env: 
  BUCK_NUM_THREADS: 3
  BUCK_PEX_LOCATION: "./new_buck.pex"

jobs:
  build_openjdk8:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Setup Android SDK 23
        uses: maxim-lobanov/setup-android-tools@v1
        with:
          packages: platforms;android-23
      - name: Run Ant Build
        run: ant
      - name: Run Buck Build
        run: ./bin/buck build buck --out "${BUCK_PEX_LOCATION}" || { cat "buck-out/log/buck-0.log"; exit 1; }
        shell: bash
      - name: Run Build Tests
        run: ${BUCK_PEX_LOCATION} build --num-threads=${BUCK_NUM_THREADS} src/... test/...
        shell: bash
